# Generated by Django 5.0.6 on 2025-02-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["id"]},
        ),
    ]
